# .github/workflows/review-pr.yml
name: Review PR with ChatGPT (secure)
on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      # SAFE: checkout the base repo at the base SHA (not attacker code)
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      # Use a pinned release of your action (not ./)
      - name: Review PR
        uses: osl-incubator/github-actions-chatgpt-pr-reviewer@1.0.7
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          openai_model: gpt-5
          openai_temperature: "0.0"
          openai_max_tokens: "16000"
          openai_extra_criteria: |
            verify SOLID principle violations;
            code should be objective;
            code should avoid redundance;
            provide concise review and focus on the key and critical parts, otherwise the review would be very extensive.
          github_token: ${{ github.token }}
          github_pr_id: ${{ github.event.pull_request.number }}
